# Site settings
title: Something About The Automatic Speech Recognition
email: xintongwang@bjfu.edu.cn
description: "bjfu speech"
baseurl: ""
url: "https://oshindow.github.io"
courseurl: "http://cs231n.stanford.edu/"
github_username: oshindow

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge